config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'top#index'
  resources :contents
  resources :contacts
  resources :comments
  resources :awards
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
     validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to contents_path, notice: "コメントしました！"
    else
      render 'new'
    end
  end

    private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:content)
    end
  end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact = Contact.new
    end
  end

  def create
    @contact = Contact.new(contacts_params)
    if @contact.save
    Contact.create(contacts_params)
    redirect_to root_path, info: "お問い合わせありがとうございました！",controller: :contacts, action: :new
    NoticeMailer.sendmail_contact(@contact).deliver
    else
    render action: 'new'
    end
  end

  private
    def contacts_params
      params.require(:contact).permit(:name, :content)
    end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to contents_path, notice: "コメントしました！"
    else
      render 'new'
    end
  end

    private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:content)
    end
  end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/awards/index.html.erb
<div class="container-fluid">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">
        <h1 class="name">
          Awards
        </h1>
        <section class="inform">
          <h1>COLLEGE</h1>
          <img src="<%= asset_path "school.jpg" %>">
        </section>
        <section class="description container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <p>
                大学では賞状を２つ頂きました。<br>
                どちらも1年次(平成26年)に頂きました。<br>
                学長賞(1位)はグループでフィールドワークを行い、八王子の問題を調査しポスターにまとめ発表するというものでした。<br>
                メディアエキスパート賞は学業成績がよい人に与えられます。
              </p>
            </div>
          </div>
        </section>

        <section class="inform">
          <h1>BADMINTON</h1>
          <img src="<%= asset_path "badminton.jpg" %>">
        </section>
        <section class="description container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <p>
                趣味のバドミントンでは平成28年に賞状を二つ頂きました。<br>
                1つはシングルスで平塚会長杯のCクラスで準優勝しました。<br>
                2つ目は所属している社会人チームで団体戦に出場し、2部で3位になりました。
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container-fluid">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <p id="notice"><%= notice %></p>
        <%= form_for(@contact) do |f| %>
        <% if @contact.errors.any? %>
        <div id="error_explanation">
          <!--# バリデーションエラーの件数を表示します。-->
          <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
          <ul>
            <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <h1 class="name">
          Contact
        </h1>
        <section class="inform">
          <h1>連絡先</h1>
        </section>
        <section class="description container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <p class="address">
                Email:M01141329f@edu.teu.ac.jp<br>
                TELL:080-2046-9445
              </p>
            </div>
          </div>
        </section>
        <section class="renraku container-fluid">
          ↓下記から直接連絡できます！↓
        </section>
        <div class="mail">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label :content %>
        <%= f.text_field :content, class: 'form-control' %>
        <br>
        <%= f.submit '送信', class: 'btn btn-primary btn-block'%>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/contents/_form.html.erb
<div class="container-fluid">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <%= form_for(@comment) do |f| %>
        <%= select_tag 'note[point]', options_for_select(["InformBacket", "Shujigram", "3"]) %><br>
        <%= f.label :content %>
        <%= f.text_field :content, class: 'form-control' %>
        <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
        <% end %>
        <%= link_to "コンテンツ一覧画面にもどる", contents_path %>
      </div>
    </div>
  </div>
</div>

app/views/contents/index.html.erb
<div class="container-fluid">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">
        <h1 class="name">
          My Contents
        </h1>
        <section class="inform">
          <h1>INFORM BACKET</h1>
          <div class="URL">
            Go to
            <a href="https://arcane-badlands-67342.herokuapp.com/">
              <div class="btn btn-default btn-sm">
                InformBacket
              </div>
            </a>
            or
            <a href="https://github.com/KawamotoShuji/sxdsns">
              <div class="btn btn-default btn-sm">
                Github
              </div>
            </a>

          </div>
          <img src="<%= asset_path "informbacket.png" %>">
        </section>
        <section class="skill container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <div class="skill-list">
                <img src="<%= asset_path "ruby.png" %>">
                <img src="<%= asset_path "rails.png" %>">
                <img src="<%= asset_path "html5.png" %>">
                <img src="<%= asset_path "css3.png" %>">
                <img src="<%= asset_path "mysql.png" %>">
                <img src="<%= asset_path "github.png" %>">
              </div>
            </div>
          </div>
        </section>
        <!-- <%= link_to '作品に対するコメントを送る', new_content_path, class: 'btn btn-default btn-sm'%> -->
        <section class="description container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <p>
                研究室内の3年生で掲示板のように気軽に情報を共有できたらいいなと思ったことがきっかけで、LINEで発言がしにくかったり小さいことでも個人的に話し合いたいことがあればここで話し合えます。
                コンセプトは情報の細分化です。
                Githubを利用して、4人でチーム開発しました。
              </p>
            </div>
          </div>
        </section>

        <section class="inform">
          <h1>SHUJIGRAM</h1>
          <div class="URL">
            Go to
            <a href="https://protected-sea-20140.herokuapp.com/">
              <div class="btn btn-default btn-sm">
                Shujigram
              </div>
            </a>
            or
            <a href="https://github.com/KawamotoShuji/modokiram">
              <div class="btn btn-default btn-sm">
                Github
              </div>
            </a>
          </div>
          <img src="<%= asset_path "shujigram.png" %>">
        </section>
        <section class="skill container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <div class="skill-list">
                <img src="<%= asset_path "ruby.png" %>">
                <img src="<%= asset_path "rails.png" %>">
                <img src="<%= asset_path "html5.png" %>">
                <img src="<%= asset_path "css3.png" %>">
                <img src="<%= asset_path "mysql.png" %>">
                <img src="<%= asset_path "github.png" %>">
                <img src="<%= asset_path "coffee.png" %>">
                <img src="<%= asset_path "bootstrap.png" %>">
                <img src="<%= asset_path "s3.png" %>">
              </div>
            </div>
          </div>
        </section>
        <!-- <%= link_to '作品に対するコメントを送る', new_content_path, class: 'btn btn-default btn-sm'%> -->
        <section class="description container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <p>
                Ruby On Railsを理解していく過程として、簡単なSNS的なものを作ろうと考えインスタグラムを真似してみました。
                とにかくなんでもやってみようということでSNSログインやメール承認機能や管理者画面などを搭載してみました
                S３により画像が消えないようにしました。
                また、ブートストラップで携帯にも対応させたりインスタグラムに雰囲気を似せるためにCSSをかなりこだわりました。
                初心者なのでかなりエラーが出ましたがなんとか乗り越えました。
              </p>
            </div>
          </div>
        </section>

        <section class="inform">
          <h1>Comfusion Comix</h1>
          <div class="URL">
            Go to
            <a href="https://youtu.be/cc5xSpI9d6s">
              <div class="btn btn-default btn-sm">
                Confusion Comix
              </div>
            </a>
          </div>
          <img src="<%= asset_path "confusion.png" %>">
        </section>
        <section class="skill container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <div class="skill-list">
                <img src="<%= asset_path "imovie.png" %>">
                <img src="<%= asset_path "mind.png" %>">
              </div>
            </div>
          </div>
        </section>
        <!-- <%= link_to '作品に対するコメントを送る', new_content_path, class: 'btn btn-default btn-sm'%> -->
        <section class="description container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <p>
                大学の授業で制作しました。
                ターゲットユーザーは漫画を趣味で書いていて、一人ではなく大人数で漫画を作り上げたい人向けです。
                提供価値は、それぞれが一コマを担当するのでその後の展開が読めなくワクワクするところです。
                カスタマージャーニーマップ、ペルソナ、二軸チャート、マインドマップ、prottなどを使用し、企画からビデオプロトタイプまで行いました。
                授業内では全体で3位になることができました。
                是非ビデオプロトタイプの動画もご覧ください。
              </p>
            </div>
          </div>
        </section>

      </div>
    </div>
  </div>
</div>

app/views/contents/new.html.erb
<h2><center>コメントを送る</center></h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shuji's Presents</title>
  <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all',:debug => true, :media => "all" %>
  <%= javascript_include_tag 'application', :debug => true  %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "KawamotoShuji", root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              <li ><%= link_to 'CONTENTS', contents_path %></li>
              <li ><%= link_to 'AWARDS', awards_path %></li>
              <li ><%= link_to 'CONTACT', new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

  <%= yield %>

  <footer>
    <small>© 2017 Copyright Shuji Kawamoto.</small>
  </footer>

</body>
</html>

app/views/top/index.html.erb
<div class="container-fluid">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">
        <section class="main-header">
          <p class="flash"><%= notice %><%= alert %></p>
          <h1 class="name">
            Shuji Kawamoto
          </h1>
          <img src="<%= asset_path "shuji.jpg" %>">
        </section>
        <section class="me container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
              <p>
                東京工科大学メディア学部メディア学科3年の河本周時と申します。<br>
                SXD(ソーシャルエクスペリエンスデザイン)研究室に所属していて、UXに関係した研究をしています！<br>
                趣味はバドミントンとバイクです！<br>
                バドミントンは中学一年から続けていて今年で10年目です！！<br>
                バイクはNinja250SLに乗っています！！<br>
                最近プログラミングを始めて、個人やチームで開発をして、技術力を高めています！！
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>